/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as GuideProbabilityRouteImport } from './routes/guide/probability'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideProbabilityRoute = GuideProbabilityRouteImport.update({
  id: '/guide/probability',
  path: '/guide/probability',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/licenses': typeof LicensesRoute
  '/guide/probability': typeof GuideProbabilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/licenses': typeof LicensesRoute
  '/guide/probability': typeof GuideProbabilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/licenses': typeof LicensesRoute
  '/guide/probability': typeof GuideProbabilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/licenses' | '/guide/probability'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/licenses' | '/guide/probability'
  id: '__root__' | '/' | '/licenses' | '/guide/probability'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LicensesRoute: typeof LicensesRoute
  GuideProbabilityRoute: typeof GuideProbabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/probability': {
      id: '/guide/probability'
      path: '/guide/probability'
      fullPath: '/guide/probability'
      preLoaderRoute: typeof GuideProbabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LicensesRoute: LicensesRoute,
  GuideProbabilityRoute: GuideProbabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
